export const fontFamilyMap = {
  anjal: 'Anjal, sans-serif',
  anjal1: 'Anjal1, sans-serif',
  bamini: 'Bamini, sans-serif',
  boomi: 'Boomi, sans-serif',
  dinakaran: 'Dinakaran, sans-serif',
  dinamani: 'Dinamani, sans-serif',
  indoweb: 'Indoweb, sans-serif',
  keyman: 'Keyman, sans-serif',
  koeln: 'Koeln, sans-serif',
  libi: 'Libi, sans-serif',
  murasoli: 'Murasoli, sans-serif',
  mylai: 'Mylai, sans-serif',
  nakkeeran: 'Nakkeeran, sans-serif',
  oldvikatan: 'Oldvikatan, sans-serif',
  roman: 'Roman, sans-serif',
  senthamizh: 'Senthamizh, sans-serif',
  tab: 'Tab, sans-serif',
  tam: 'Tam, sans-serif',
  thanthy: 'Thanthy, sans-serif',
  tscii: 'Tscii, sans-serif',
  webulagam: 'Webulagam, sans-serif',
  unicode: 'Unicode, Baloo Thambi 2, sans-serif',
};

export default fontFamilyMap;
